name: Setup React Native
description: Set up a specific version of React Native
inputs:
  version:
    description: The React Native version to set up
    required: true
runs:
  using: composite
  steps:
    - name: Disable minimum age gate
      run: |
        yarn config unset npmMinimalAgeGate
      shell: bash
    - name: Set up react-native@${{ inputs.version }}
      run: |
        rm example/ios/Podfile.lock
        rm example/macos/Podfile.lock
        rm example/visionos/Podfile.lock
        node --run set-react-version -- ${{ inputs.version }}
      shell: bash
      working-directory: packages/app
