name: Setup React Native
description: Set up a specific version of React Native
inputs:
  version:
    description: The React Native version to set up
    required: true
runs:
  using: composite
  steps:
    - name: Set up react-native@${{ inputs.version }}
      run: |
        rm example/ios/Podfile.lock
        rm example/macos/Podfile.lock
        rm example/visionos/Podfile.lock
        npm run set-react-version -- ${{ inputs.version }}
        node --eval "require('./android/gradle-wrapper.js').configureGradleWrapper('example/android')"
      shell: bash
