require_relative 'node_modules/react-native-test-app/test_app.rb'

workspace 'Example.xcworkspace'

add_app_pods = Proc.new {
  pod 'Example-dev', :path => '.'
}

add_test_pods = Proc.new {
  pod 'Example-Tests', :path => '.'
}

use_test_app!(__dir__, :add_app_pods => add_app_pods, :add_test_pods => add_test_pods)
