"platform: Android":
  - android/**/*
  - example/android/**/*
  - test/android-test-app/**/*
  - test-app.gradle
"platform: iOS":
  - ReactTestApp-DevSupport.podspec
  - example/ios/**/*
  - ios/**/*
  - test/*.rb
  - test_app.rb
"platform: macOS":
  - ReactTestApp-DevSupport.podspec
  - example/macos/**/*
  - ios/*.rb
  - ios/ReactTestApp/Manifest.swift
  - ios/ReactTestApp/React+Compatibility.{h,m}
  - ios/ReactTestApp/ReactInstance.swift
  - ios/ReactTestApp/ReactTestApp-Bridging-Header.h
  - ios/ReactTestApp/Session.swift
  - ios/ReactTestApp/UIViewController+ReactTestApp.{h,m}
  - macos/**/*
  - test/*.rb
"platform: Windows":
  - example/windows/**/*
  - test/windows-test-app/**/*
  - windows/**/*
