"platform: Android":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/gradle/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - android/**/*
          - common/**/*
          - example/android/**/*
          - scripts/*.js
          - test/android-test-app/**/*
          - test-app.gradle
"platform: iOS":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/cocoapods/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - Gemfile*
          - ReactTestApp-DevSupport.podspec
          - common/**/*
          - example/ios/**/*
          - ios/**/*
          - scripts/*.js
          - scripts/xcodebuild.sh
          - test/*.rb
          - test_app.rb
"platform: macOS":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/cocoapods/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - Gemfile*
          - ReactTestApp-DevSupport.podspec
          - common/**/*
          - example/macos/**/*
          - ios/*.rb
          - ios/ReactTestApp/Manifest.swift
          - ios/ReactTestApp/React+Compatibility.{h,m}
          - ios/ReactTestApp/ReactInstance.swift
          - ios/ReactTestApp/ReactTestApp-Bridging-Header.h
          - ios/ReactTestApp/Session.swift
          - ios/ReactTestApp/UIViewController+ReactTestApp.{h,m}
          - macos/**/*
          - scripts/*.js
          - scripts/xcodebuild.sh
          - test/*.rb
"platform: visionOS":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/cocoapods/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - Gemfile*
          - ReactTestApp-DevSupport.podspec
          - common/**/*
          - example/visionos/**/*
          - ios/*.rb
          - ios/ReactTestApp/Manifest.swift
          - ios/ReactTestApp/React+Compatibility.{h,m}
          - ios/ReactTestApp/ReactInstance.swift
          - ios/ReactTestApp/ReactTestApp-Bridging-Header.h
          - ios/ReactTestApp/Session.swift
          - ios/ReactTestApp/UIViewController+ReactTestApp.{h,m}
          - visionos/**/*
          - scripts/*.js
          - scripts/xcodebuild.sh
          - test/*.rb
"platform: Windows":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - common/**/*
          - example/windows/**/*
          - scripts/*.ps1
          - scripts/*.js
          - test/windows-test-app/**/*
          - windows/**/*
