"platform: Android":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/gradle/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - packages/app/android/**/*
          - packages/app/common/**/*
          - packages/app/example/android/**/*
          - packages/app/scripts/*.js
          - packages/app/scripts/configure.mjs
          - packages/app/scripts/embed-manifest/kotlin.mjs
          - packages/app/scripts/embed-manifest/main.mjs
          - packages/app/scripts/embed-manifest/validate.mjs
          - packages/app/scripts/init.mjs
          - packages/app/scripts/template.mjs
          - packages/app/test-app.gradle
"platform: iOS":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/cocoapods/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - Gemfile*
          - packages/app/ReactTestApp-DevSupport.podspec
          - packages/app/common/**/*
          - packages/app/example/ios/**/*
          - packages/app/ios/**/*
          - packages/app/scripts/*.js
          - packages/app/scripts/configure.mjs
          - packages/app/scripts/embed-manifest/main.mjs
          - packages/app/scripts/embed-manifest/swift.mjs
          - packages/app/scripts/embed-manifest/validate.mjs
          - packages/app/scripts/init.mjs
          - packages/app/scripts/template.mjs
          - packages/app/scripts/build/xcodebuild.sh
          - packages/app/test_app.rb
"platform: macOS":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/cocoapods/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - Gemfile*
          - packages/app/ReactTestApp-DevSupport.podspec
          - packages/app/common/**/*
          - packages/app/example/macos/**/*
          - packages/app/ios/*.rb
          - packages/app/ios/ReactTestApp/Manifest.swift
          - packages/app/ios/ReactTestApp/React+Compatibility.{h,m}
          - packages/app/ios/ReactTestApp/ReactInstance.swift
          - packages/app/ios/ReactTestApp/ReactTestApp-Bridging-Header.h
          - packages/app/ios/ReactTestApp/Session.swift
          - packages/app/ios/ReactTestApp/UIViewController+ReactTestApp.{h,m}
          - packages/app/macos/**/*
          - packages/app/scripts/*.js
          - packages/app/scripts/configure.mjs
          - packages/app/scripts/embed-manifest/main.mjs
          - packages/app/scripts/embed-manifest/swift.mjs
          - packages/app/scripts/embed-manifest/validate.mjs
          - packages/app/scripts/init.mjs
          - packages/app/scripts/template.mjs
          - packages/app/scripts/build/xcodebuild.sh
          - packages/example-macos/**/*
"platform: visionOS":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/cocoapods/*
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - Gemfile*
          - packages/app/ReactTestApp-DevSupport.podspec
          - packages/app/common/**/*
          - packages/app/example/visionos/**/*
          - packages/app/ios/*.rb
          - packages/app/ios/ReactTestApp/*.{h,m,mm,swift}
          - packages/app/scripts/*.js
          - packages/app/scripts/configure.mjs
          - packages/app/scripts/embed-manifest/main.mjs
          - packages/app/scripts/embed-manifest/swift.mjs
          - packages/app/scripts/embed-manifest/validate.mjs
          - packages/app/scripts/init.mjs
          - packages/app/scripts/template.mjs
          - packages/app/scripts/build/xcodebuild.sh
          - packages/app/visionos/**/*
"platform: Windows":
  - changed-files:
      - any-glob-to-any-file:
          - .github/actions/init-test-app/*
          - .github/actions/setup-toolchain/*
          - .github/workflows/build.yml
          - packages/app/common/**/*
          - packages/app/example/windows/**/*
          - packages/app/scripts/*.ps1
          - packages/app/scripts/*.js
          - packages/app/scripts/configure.mjs
          - packages/app/scripts/embed-manifest/cpp.mjs
          - packages/app/scripts/embed-manifest/main.mjs
          - packages/app/scripts/embed-manifest/validate.mjs
          - packages/app/scripts/init.mjs
          - packages/app/scripts/template.mjs
          - packages/app/windows/**/*
          - packages/example-windows/**/*
