"platform: Android":
  - android/**/*
  - example/android/**/*
  - test-app.gradle
"platform: iOS":
  - ReactTestApp-DevSupport.podspec
  - example/ios/**/*
  - ios/**/*
  - test_app.rb
"platform: macOS":
  - ReactTestApp-DevSupport.podspec
  - example/macos/**/*
  - ios/ReactTestApp/Manifest.swift
  - ios/ReactTestApp/React+Compatibility.{h,m}
  - ios/ReactTestApp/ReactInstance.swift
  - ios/ReactTestApp/ReactTestApp-Bridging-Header.h
  - ios/ReactTestApp/Session.swift
  - ios/ReactTestApp/UIViewController+ReactTestApp.{h,m}
  - macos/**/*
"platform: Windows":
  - example/windows/**/*
  - windows/**/*
