name: Yarn
description: Runs `yarn install` and caches downloaded dependencies
inputs:
  immutable:
    description: Abort with an error exit code if the lockfile was to be modified
    default: true
runs:
  using: composite
  steps:
    - name: Cache /.yarn/cache
      uses: actions/cache@v2
      with:
        path: .yarn/cache
        key: ${{ hashFiles('yarn.lock') }}
    - name: Install npm dependencies
      if: ${{ inputs.immutable }}
      run: yarn
      shell: bash
    - name: Install npm dependencies (ignore lockfile changes)
      if: ${{ !inputs.immutable }}
      run: yarn --no-immutable
      shell: bash
