AllCops:
  NewCops: enable
  Include:
    - "**/*.rb"
    - Gemfile
  Exclude:
    - "**/node_modules/**/*"
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  IgnoredMethods: [make_project!, use_test_app_internal!]

Metrics/PerceivedComplexity:
  IgnoredMethods: [make_project!, use_test_app_internal!]

Naming/FileName:
  Exclude:
    - !ruby/regexp /-\d+\.\d+\.rb$/
    - "**/*.podspec"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
