catalog:
  "@babel/core": ^7.25.2
  "@babel/preset-env": ^7.25.3
  "@react-native-webapis/web-storage": ^0.4.6
  "@types/node": ^24.0.0
  "@rnx-kit/cli": ^2.0.1
  "@rnx-kit/metro-config": ^2.2.4
  "@rnx-kit/polyfills": ^0.3.0
  "@rnx-kit/tsconfig": ^3.0.1
compressionLevel: 0
enableGlobalCache: false
enableScripts: false
enableTelemetry: false
globalFolder: .yarn/berry # Workaround for 'EXDEV: cross-device link not permitted' errors on GHA
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
  - code: YN0069 # This rule seems redundant when applied on the original package
    level: error
nodeLinker: pnpm
npmMinimalAgeGate: 7d
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
  appium@3:
    dependencies:
      "@colors/colors": ^1.6.0
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - path: .yarn/plugins/clean.cjs
  - path: .yarn/plugins/undo-bin-sorting.cjs
  - checksum: 8d8252c376e41a67ca509b2778f3fb92164aa91828459ae8a6aa0e13f1b6f9843586d0983ba9a200f6d813d37efc171474c8dbc85b0dff01df56c0d476c238ce
    path: .yarn/plugins/@rnx-kit/yarn-plugin-ignore.cjs
    spec: "https://raw.githubusercontent.com/microsoft/rnx-kit/main/incubator/yarn-plugin-ignore/dist/yarn-plugin-ignore.cjs"
tsEnableAutoTypes: false
yarnPath: .yarn/releases/yarn-4.13.0.cjs
