compressionLevel: 0
enableGlobalCache: false
enableScripts: false
enableTelemetry: false
logFilters:
  - code: YN0007 # X must be built because it never has been before or the last one failed
    level: discard
  - code: YN0008 # X must be rebuilt because its dependency tree changed
    level: discard
  - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
    level: discard
  - code: YN0069 # This rule seems redundant when applied on the original package
    level: error
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
packageExtensions:
  babel-plugin-transform-flow-enums@*:
    peerDependencies:
      "@babel/core": ^7.20.0
  memfs@4.x:
    peerDependenciesMeta:
      memfs:
        optional: true
      quill-delta:
        optional: true
      rxjs:
        optional: true
      tslib:
        optional: true
  react-native-macos@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
      react-native: "*"
  react-native-windows@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"
  - path: .yarn/plugins/clean.cjs
  - path: .yarn/plugins/link-project.cjs
  - path: .yarn/plugins/boost-workaround.cjs
tsEnableAutoTypes: false
yarnPath: .yarn/releases/yarn-4.3.0.cjs
