// This file was generated by generate-manifest.mjs.
// DO NOT MODIFY. ALL CHANGES WILL BE OVERWRITTEN.

@file:Suppress("ktlint:standard:trailing-comma-on-declaration-site")

package com.microsoft.reacttestapp.manifest

import android.os.Bundle

data class Component(
    val appKey: String,
    val displayName: String?,
    val initialProperties: Bundle?,
    val presentationStyle: String?,
    val slug: String?,
)

data class Manifest(
    val name: String,
    val displayName: String,
    val version: String?,
    val bundleRoot: String?,
    val singleApp: String?,
    val components: List<Component>?,
)
