ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until File.exist?("#{ws_dir}/node_modules/react-native-test-app/visionos/test_app.rb") &&
                             ws_dir.expand_path.to_s != '/'
require "#{ws_dir}/node_modules/react-native-test-app/visionos/test_app.rb"

workspace 'Example.xcworkspace'

options = {
  :fabric_enabled => false,
  :bridgless_enabled => false,
  :hermes_enabled => false,
}

use_test_app! options do |target|
  target.tests do
    pod 'Example-Tests', :path => '..'
  end
end
