name: Create React Native Test App
description: Initializes a new test app
inputs:
  arguments:
    required: true
runs:
  using: composite
  steps:
    - name: Disable minimum age gate
      run: |
        yarn config unset npmMinimalAgeGate
      shell: bash
    - name: Install
      run: |
        scripts/install-test-template.sh --version highest ${{ inputs.arguments }}
      shell: bash
    - name: Initialize a new app
      run: |
        yarn init-test-app --destination test-app --name TestApp ${{ inputs.arguments }}
      shell: bash
      working-directory: template-example
