name: Create React Native Test App
description: Initializes a new test app
inputs:
  platform:
    description: The platform to create a test app for
    required: true
runs:
  using: composite
  steps:
    - name: Generate cache key
      id: cache-key-generator
      run: echo "::set-output name=cache-key::$(node scripts/shasum.mjs yarn.lock)"
      shell: bash
    - name: Cache /.yarn/cache
      uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: yarn-true-${{ steps.cache-key-generator.outputs.cache-key }}
    - name: Install
      run: |
        scripts/install-test-template.sh ${{ inputs.platform }}
      shell: bash
    - name: react-native init-test-app
      run: |
        npx react-native init-test-app --destination test-app --name TestApp --platform ${{ inputs.platform }}
      shell: bash
      working-directory: template-example
