name: Create React Native Test App
description: Initializes a new test app
inputs:
  platform:
    description: The platform to create a test app for
    required: true
runs:
  using: composite
  steps:
    - name: Install
      run: |
        scripts/install-test-template.sh ${{ inputs.platform }}
      shell: bash
    - name: Initialize a new app
      run: |
        if [[ ${{ inputs.platform }} == "all" ]]; then
          yarn init-test-app --destination test-app --name TestApp -p android -p ios -p macos -p windows
        else
          yarn init-test-app --destination test-app --name TestApp --platform ${{ inputs.platform }}
        fi
      shell: bash
      working-directory: template-example
    - name: Workaround for 'Verification checksum was incorrect' (iOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        if [[ ${{ inputs.platform }} != "macos" ]]; then
          cd react-native
          patch < ../../../.yarn/patches/react-native-npm-0.72.8-5af30d9693.patch
        fi
      shell: bash
      working-directory: template-example/node_modules
    - name: Workaround for 'Verification checksum was incorrect' (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        if [[ ${{ inputs.platform }} != "ios" ]]; then
          cd react-native-macos
          patch < ../../../.yarn/patches/react-native-macos-npm-0.72.12-61bf1f8441.patch
        fi
      shell: bash
      working-directory: template-example/node_modules
