#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

extern NSNotificationName const ReactTestAppDidInitializeNotification;

extern NSNotificationName const ReactTestAppWillInitializeReactNativeNotification;
extern NSNotificationName const ReactTestAppDidInitializeReactNativeNotification;
extern NSNotificationName const ReactTestAppDidRegisterAppsNotification;

extern NSNotificationName const ReactTestAppSceneDidOpenURLNotification;

extern NSNotificationName const ReactInstanceDidLoadBundle;

NS_ASSUME_NONNULL_END
