import { deepEqual } from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import { generateInfoPlist as generateInfoPlistActual } from "../../ios/infoPlist.mjs";
import { readTextFile } from "../../scripts/helpers.js";
import type { JSONObject } from "../../scripts/types.ts";
import { mkdir_p } from "../../scripts/utils/filesystem.mjs";
import { fs, setMockFiles } from "../fs.mock.ts";

const macosOnly = { skip: process.platform === "win32" };

describe("generateInfoPlist()", macosOnly, () => {
  const targetPlatforms = ["ios", "macos", "visionos"] as const;

  function generateInfoPlist(
    config: JSONObject,
    platform: (typeof targetPlatforms)[number]
  ): void {
    const destination = ".";
    mkdir_p(destination, fs);
    generateInfoPlistActual(config, platform, destination, fs);
  }

  function readInfoPlist() {
    return readTextFile("Info.plist", fs).split("\n");
  }

  afterEach(() => {
    setMockFiles();
  });

  for (const platform of targetPlatforms) {
    it(`[${platform}] generates a default 'Info.plist'`, () => {
      generateInfoPlist({}, platform);

      deepEqual(readInfoPlist(), DEFAULT_INFO_PLIST[platform]);
    });

    it(`[${platform}] registers font files`, () => {
      generateInfoPlist(
        { resources: ["OpenType.otf", "TrueType.ttf"] },
        platform
      );

      deepEqual(readInfoPlist(), INFO_PLIST_WITH_FONTS[platform]);
    });

    it(`[${platform}] registers platform specific font files`, () => {
      generateInfoPlist(
        { resources: { [platform]: ["OpenType.otf", "TrueType.ttf"] } },
        platform
      );

      deepEqual(readInfoPlist(), INFO_PLIST_WITH_FONTS[platform]);
    });
  }

  it("[macos] sets application category type", () => {
    generateInfoPlist(
      { macos: { applicationCategoryType: "public.app-category.games" } },
      "macos"
    );

    deepEqual(readInfoPlist(), INFO_PLIST_MACOS.applicationCategoryType);
  });

  it("[macos] sets human-readable copyright", () => {
    generateInfoPlist(
      {
        macos: {
          humanReadableCopyright:
            "Copyright © 2025 Contoso. All rights reserved.",
        },
      },
      "macos"
    );

    deepEqual(readInfoPlist(), INFO_PLIST_MACOS.humanReadableCopyright);
  });
});

const DEFAULT_INFO_PLIST = {
  ios: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleURLTypes</key>",
    "	<array>",
    "		<dict>",
    "			<key>CFBundleURLSchemes</key>",
    "			<array>",
    "				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "				<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "			</array>",
    "		</dict>",
    "	</array>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationQueriesSchemes</key>",
    "	<array>",
    "		<string>linkedin</string>",
    "		<string>ms-outlook</string>",
    "		<string>ms-sfb</string>",
    "		<string>msauth</string>",
    "		<string>msauthv2</string>",
    "		<string>msauthv3</string>",
    "	</array>",
    "	<key>LSRequiresIPhoneOS</key>",
    "	<false/>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>NSCameraUsageDescription</key>",
    "	<string>The camera is needed to scan QR codes for JS bundle URLs</string>",
    "	<key>UIApplicationSceneManifest</key>",
    "	<dict>",
    "		<key>UIApplicationSupportsMultipleScenes</key>",
    "		<true/>",
    "		<key>UISceneConfigurations</key>",
    "		<dict>",
    "			<key>UIWindowSceneSessionRoleApplication</key>",
    "			<array>",
    "				<dict>",
    "					<key>UISceneConfigurationName</key>",
    "					<string>Default Configuration</string>",
    "					<key>UISceneDelegateClassName</key>",
    "					<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>",
    "				</dict>",
    "			</array>",
    "		</dict>",
    "	</dict>",
    "	<key>UILaunchScreen</key>",
    "	<dict/>",
    "	<key>UIRequiredDeviceCapabilities</key>",
    "	<array>",
    "		<string>arm64</string>",
    "	</array>",
    "	<key>UISupportedInterfaceOrientations</key>",
    "	<array>",
    "		<string>UIInterfaceOrientationPortrait</string>",
    "		<string>UIInterfaceOrientationPortraitUpsideDown</string>",
    "		<string>UIInterfaceOrientationLandscapeLeft</string>",
    "		<string>UIInterfaceOrientationLandscapeRight</string>",
    "	</array>",
    "	<key>UIViewControllerBasedStatusBarAppearance</key>",
    "	<false/>",
    "</dict>",
    "</plist>",
    "",
  ],
  macos: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationCategoryType</key>",
    "	<string>public.app-category.developer-tools</string>",
    "	<key>LSMinimumSystemVersion</key>",
    "	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>NSHumanReadableCopyright</key>",
    "	<string>Copyright © 2020 Microsoft. All rights reserved.</string>",
    "	<key>NSMainStoryboardFile</key>",
    "	<string>Main</string>",
    "	<key>NSPrincipalClass</key>",
    "	<string>NSApplication</string>",
    "	<key>NSSupportsAutomaticTermination</key>",
    "	<true/>",
    "	<key>NSSupportsSuddenTermination</key>",
    "	<true/>",
    "</dict>",
    "</plist>",
    "",
  ],
  visionos: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleURLTypes</key>",
    "	<array>",
    "		<dict>",
    "			<key>CFBundleURLSchemes</key>",
    "			<array>",
    "				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "				<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "			</array>",
    "		</dict>",
    "	</array>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationQueriesSchemes</key>",
    "	<array>",
    "		<string>linkedin</string>",
    "		<string>ms-outlook</string>",
    "		<string>ms-sfb</string>",
    "		<string>msauth</string>",
    "		<string>msauthv2</string>",
    "		<string>msauthv3</string>",
    "	</array>",
    "	<key>LSRequiresIPhoneOS</key>",
    "	<false/>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>UIApplicationSceneManifest</key>",
    "	<dict>",
    "		<key>UIApplicationSupportsMultipleScenes</key>",
    "		<true/>",
    "		<key>UISceneConfigurations</key>",
    "		<dict>",
    "			<key>UIWindowSceneSessionRoleApplication</key>",
    "			<array>",
    "				<dict>",
    "					<key>UISceneConfigurationName</key>",
    "					<string>Default Configuration</string>",
    "					<key>UISceneDelegateClassName</key>",
    "					<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>",
    "				</dict>",
    "			</array>",
    "		</dict>",
    "	</dict>",
    "	<key>UILaunchScreen</key>",
    "	<dict/>",
    "	<key>UIRequiredDeviceCapabilities</key>",
    "	<array>",
    "		<string>arm64</string>",
    "	</array>",
    "	<key>UISupportedInterfaceOrientations</key>",
    "	<array>",
    "		<string>UIInterfaceOrientationPortrait</string>",
    "		<string>UIInterfaceOrientationPortraitUpsideDown</string>",
    "		<string>UIInterfaceOrientationLandscapeLeft</string>",
    "		<string>UIInterfaceOrientationLandscapeRight</string>",
    "	</array>",
    "	<key>UIViewControllerBasedStatusBarAppearance</key>",
    "	<false/>",
    "</dict>",
    "</plist>",
    "",
  ],
};

const INFO_PLIST_WITH_FONTS = {
  ios: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleURLTypes</key>",
    "	<array>",
    "		<dict>",
    "			<key>CFBundleURLSchemes</key>",
    "			<array>",
    "				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "				<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "			</array>",
    "		</dict>",
    "	</array>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationQueriesSchemes</key>",
    "	<array>",
    "		<string>linkedin</string>",
    "		<string>ms-outlook</string>",
    "		<string>ms-sfb</string>",
    "		<string>msauth</string>",
    "		<string>msauthv2</string>",
    "		<string>msauthv3</string>",
    "	</array>",
    "	<key>LSRequiresIPhoneOS</key>",
    "	<false/>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>NSCameraUsageDescription</key>",
    "	<string>The camera is needed to scan QR codes for JS bundle URLs</string>",
    "	<key>UIAppFonts</key>",
    "	<array>",
    "		<string>OpenType.otf</string>",
    "		<string>TrueType.ttf</string>",
    "	</array>",
    "	<key>UIApplicationSceneManifest</key>",
    "	<dict>",
    "		<key>UIApplicationSupportsMultipleScenes</key>",
    "		<true/>",
    "		<key>UISceneConfigurations</key>",
    "		<dict>",
    "			<key>UIWindowSceneSessionRoleApplication</key>",
    "			<array>",
    "				<dict>",
    "					<key>UISceneConfigurationName</key>",
    "					<string>Default Configuration</string>",
    "					<key>UISceneDelegateClassName</key>",
    "					<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>",
    "				</dict>",
    "			</array>",
    "		</dict>",
    "	</dict>",
    "	<key>UILaunchScreen</key>",
    "	<dict/>",
    "	<key>UIRequiredDeviceCapabilities</key>",
    "	<array>",
    "		<string>arm64</string>",
    "	</array>",
    "	<key>UISupportedInterfaceOrientations</key>",
    "	<array>",
    "		<string>UIInterfaceOrientationPortrait</string>",
    "		<string>UIInterfaceOrientationPortraitUpsideDown</string>",
    "		<string>UIInterfaceOrientationLandscapeLeft</string>",
    "		<string>UIInterfaceOrientationLandscapeRight</string>",
    "	</array>",
    "	<key>UIViewControllerBasedStatusBarAppearance</key>",
    "	<false/>",
    "</dict>",
    "</plist>",
    "",
  ],
  macos: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>ATSApplicationFontsPath</key>",
    "	<string>.</string>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationCategoryType</key>",
    "	<string>public.app-category.developer-tools</string>",
    "	<key>LSMinimumSystemVersion</key>",
    "	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>NSHumanReadableCopyright</key>",
    "	<string>Copyright © 2020 Microsoft. All rights reserved.</string>",
    "	<key>NSMainStoryboardFile</key>",
    "	<string>Main</string>",
    "	<key>NSPrincipalClass</key>",
    "	<string>NSApplication</string>",
    "	<key>NSSupportsAutomaticTermination</key>",
    "	<true/>",
    "	<key>NSSupportsSuddenTermination</key>",
    "	<true/>",
    "</dict>",
    "</plist>",
    "",
  ],
  visionos: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleURLTypes</key>",
    "	<array>",
    "		<dict>",
    "			<key>CFBundleURLSchemes</key>",
    "			<array>",
    "				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "				<string>msauth.$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "			</array>",
    "		</dict>",
    "	</array>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationQueriesSchemes</key>",
    "	<array>",
    "		<string>linkedin</string>",
    "		<string>ms-outlook</string>",
    "		<string>ms-sfb</string>",
    "		<string>msauth</string>",
    "		<string>msauthv2</string>",
    "		<string>msauthv3</string>",
    "	</array>",
    "	<key>LSRequiresIPhoneOS</key>",
    "	<false/>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>UIAppFonts</key>",
    "	<array>",
    "		<string>OpenType.otf</string>",
    "		<string>TrueType.ttf</string>",
    "	</array>",
    "	<key>UIApplicationSceneManifest</key>",
    "	<dict>",
    "		<key>UIApplicationSupportsMultipleScenes</key>",
    "		<true/>",
    "		<key>UISceneConfigurations</key>",
    "		<dict>",
    "			<key>UIWindowSceneSessionRoleApplication</key>",
    "			<array>",
    "				<dict>",
    "					<key>UISceneConfigurationName</key>",
    "					<string>Default Configuration</string>",
    "					<key>UISceneDelegateClassName</key>",
    "					<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>",
    "				</dict>",
    "			</array>",
    "		</dict>",
    "	</dict>",
    "	<key>UILaunchScreen</key>",
    "	<dict/>",
    "	<key>UIRequiredDeviceCapabilities</key>",
    "	<array>",
    "		<string>arm64</string>",
    "	</array>",
    "	<key>UISupportedInterfaceOrientations</key>",
    "	<array>",
    "		<string>UIInterfaceOrientationPortrait</string>",
    "		<string>UIInterfaceOrientationPortraitUpsideDown</string>",
    "		<string>UIInterfaceOrientationLandscapeLeft</string>",
    "		<string>UIInterfaceOrientationLandscapeRight</string>",
    "	</array>",
    "	<key>UIViewControllerBasedStatusBarAppearance</key>",
    "	<false/>",
    "</dict>",
    "</plist>",
    "",
  ],
};

const INFO_PLIST_MACOS = {
  applicationCategoryType: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationCategoryType</key>",
    "	<string>public.app-category.games</string>",
    "	<key>LSMinimumSystemVersion</key>",
    "	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>NSHumanReadableCopyright</key>",
    "	<string>Copyright © 2020 Microsoft. All rights reserved.</string>",
    "	<key>NSMainStoryboardFile</key>",
    "	<string>Main</string>",
    "	<key>NSPrincipalClass</key>",
    "	<string>NSApplication</string>",
    "	<key>NSSupportsAutomaticTermination</key>",
    "	<true/>",
    "	<key>NSSupportsSuddenTermination</key>",
    "	<true/>",
    "</dict>",
    "</plist>",
    "",
  ],
  humanReadableCopyright: [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    "<dict>",
    "	<key>CFBundleDevelopmentRegion</key>",
    "	<string>$(DEVELOPMENT_LANGUAGE)</string>",
    "	<key>CFBundleDisplayName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundleExecutable</key>",
    "	<string>$(EXECUTABLE_NAME)</string>",
    "	<key>CFBundleIdentifier</key>",
    "	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>",
    "	<key>CFBundleInfoDictionaryVersion</key>",
    "	<string>6.0</string>",
    "	<key>CFBundleName</key>",
    "	<string>$(PRODUCT_DISPLAY_NAME)</string>",
    "	<key>CFBundlePackageType</key>",
    "	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>",
    "	<key>CFBundleShortVersionString</key>",
    "	<string>$(PRODUCT_VERSION)</string>",
    "	<key>CFBundleVersion</key>",
    "	<string>$(PRODUCT_BUILD_NUMBER)</string>",
    "	<key>LSApplicationCategoryType</key>",
    "	<string>public.app-category.developer-tools</string>",
    "	<key>LSMinimumSystemVersion</key>",
    "	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>",
    "	<key>NSAppTransportSecurity</key>",
    "	<dict>",
    "		<key>NSAllowsLocalNetworking</key>",
    "		<true/>",
    "	</dict>",
    "	<key>NSHumanReadableCopyright</key>",
    "	<string>Copyright © 2025 Contoso. All rights reserved.</string>",
    "	<key>NSMainStoryboardFile</key>",
    "	<string>Main</string>",
    "	<key>NSPrincipalClass</key>",
    "	<string>NSApplication</string>",
    "	<key>NSSupportsAutomaticTermination</key>",
    "	<true/>",
    "	<key>NSSupportsSuddenTermination</key>",
    "	<true/>",
    "</dict>",
    "</plist>",
    "",
  ],
};
