require_relative '../node_modules/react-native-test-app/test_app'

workspace 'Example.xcworkspace'

use_flipper! false if ENV['DISABLE_FLIPPER']

use_test_app! :fabric_enabled => false, :hermes_enabled => false do |target|
  target.tests do
    pod 'Example-Tests', :path => '..'
  end
end
