require_relative '../node_modules/react-native-test-app/test_app'

workspace 'Example.xcworkspace'

use_flipper!({ 'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3' })

use_test_app! do |target|
  target.tests do
    pod 'Example-Tests', :path => '..'
  end
end
