namespace ReactTestApp
{
    runtimeclass ComponentViewModel
    {
        String AppKey
        {
            get;
        };

        String DisplayName
        {
            get;
        };
    }
}  // namespace ReactTestApp
