name: Gradle Build
description: Executes a Gradle build
inputs:
  arguments:
    description: Gradle will execute a build with the provided arguments
    default: --no-daemon --parallel clean build check test
  project-root:
    description: The path to the root of the project
    required: true
runs:
  using: composite
  steps:
    - name: Configure Gradle wrapper
      run: |
        node --eval "require('./android/gradle-wrapper.js').configureGradleWrapper('${{ inputs.project-root }}/android')"
      shell: bash
    - name: Build
      run: ./gradlew ${{ inputs.arguments }}
      shell: bash
      working-directory: ${{ inputs.project-root }}/android
