name: Gradle Build
description: Executes a Gradle build
inputs:
  arguments:
    description: Gradle will execute a build with the provided arguments
    default: --no-daemon --parallel clean build check test
  project-root:
    description: The path to the root of the project
    required: true
runs:
  using: composite
  steps:
    - name: Configure Gradle wrapper
      run: |
        node --eval "require('./packages/app/android/gradle-wrapper.js').configureGradleWrapper('${{ inputs.project-root }}/android')"
      shell: bash
    - name: Build
      if: ${{ runner.os != 'Windows' }}
      run: ./gradlew ${{ inputs.arguments }}
      shell: bash
      working-directory: ${{ inputs.project-root }}/android
    - name: Build (Windows)
      if: ${{ runner.os == 'Windows' }}
      env:
        # https://github.com/ninja-build/ninja/issues/1900
        CMAKE_MAKE_PROGRAM: "C:\\ProgramData\\Chocolatey\\bin\\ninja.exe"
      run: ./gradlew ${{ inputs.arguments }}
      shell: bash
      working-directory: ${{ inputs.project-root }}/android
