name: Gradle Build
description: Executes a Gradle build
inputs:
  project-root:
    description: The path to the root of the project
    required: true
runs:
  using: composite
  steps:
    - name: Determine build root directory
      id: build-root-directory-finder
      run: |
        if [[ -f android/build.gradle ]]; then
          echo "::set-output name=build-root-directory::${{ inputs.project-root }}/android"
        else
          echo "::set-output name=build-root-directory::${{ inputs.project-root }}"
        fi
      shell: bash
      working-directory: ${{ inputs.project-root }}
    - name: Configure JVM memory
      env:
        JVM_ARGS: org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
      run: |
        echo $JVM_ARGS >> ${{ steps.build-root-directory-finder.outputs.build-root-directory }}/gradle.properties
      shell: bash
    - name: Build
      uses: gradle/gradle-build-action@v2.1.0
      with:
        gradle-version: wrapper
        arguments: --no-daemon clean build check test
        build-root-directory: ${{ steps.build-root-directory-finder.outputs.build-root-directory }}
