name: Gradle Build
description: Executes a Gradle build
inputs:
  arguments:
    description: Gradle will execute a build with the provided arguments
    default: --no-daemon --parallel clean build check test
  project-root:
    description: The path to the root of the project
    required: true
runs:
  using: composite
  steps:
    - name: Determine build root directory
      id: build-root-directory-finder
      run: |
        if [[ -f android/build.gradle ]]; then
          echo "build-root-directory=${{ inputs.project-root }}/android" >> $GITHUB_OUTPUT
        else
          echo "build-root-directory=${{ inputs.project-root }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
      working-directory: ${{ inputs.project-root }}
    - name: Build
      uses: gradle/gradle-build-action@v2.7.1
      with:
        gradle-version: wrapper
        build-root-directory: ${{ steps.build-root-directory-finder.outputs.build-root-directory }}
        gradle-home-cache-excludes: |
          caches
          jdks
        arguments: ${{ inputs.arguments }}
        gradle-home-cache-cleanup: true
