// This file was generated by generate-manifest.js.
// DO NOT MODIFY. ALL CHANGES WILL BE OVERWRITTEN.

struct Component: Decodable {
    let appKey: String
    let displayName: String?
    let initialProperties: [AnyHashable: Any]?
    let presentationStyle: String?
    let slug: String?
}

struct Manifest: Decodable {
    let name: String
    let displayName: String
    let bundleRoot: String?
    let singleApp: String?
    let components: [Component]?
}
