name: CocoaPods
description: Runs `pod install` and caches installed dependencies
inputs:
  project-directory:
    description: The path to the root of the project directory
    required: true
  working-directory:
    description: The directory where commands are run
    required: true
runs:
  using: composite
  steps:
    - name: Generate cache key
      id: cache-key-generator
      run: echo '::set-output name=cache-key::${{ inputs.working-directory }}/${{ inputs.project-directory }}/Podfile.lock'
      shell: bash
    - name: Cache /${{ inputs.working-directory }}/${{ inputs.project-directory }}/Pods
      uses: actions/cache@v2
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.project-directory }}/Pods
        key: ${{ hashFiles(steps.cache-key-generator.outputs.cache-key) }}
    - name: Install Pods
      run: |
        pod install --project-directory=${{ inputs.project-directory }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
