name: CocoaPods
description: Runs `pod install` and caches installed dependencies
inputs:
  project-directory:
    description: The path to the root of the project directory
    required: true
  working-directory:
    description: The directory where commands are run
    required: true
runs:
  using: composite
  steps:
    - name: Find `Podfile.lock`
      id: find-lockfile
      run: |
        podfile_lock="${{ inputs.working-directory }}/${{ inputs.project-directory }}/Podfile.lock"
        if [[ -f "$podfile_lock" ]]; then
          echo "path=$podfile_lock" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Cache /${{ inputs.working-directory }}/${{ inputs.project-directory }}/Pods
      if: ${{ steps.find-lockfile.outputs.path }}
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-directory }}/${{ inputs.project-directory }}/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles(steps.find-lockfile.outputs.path) }}
    - name: Install Pods
      run: |
        pod install --project-directory=${{ inputs.project-directory }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
