name: Setup toolchain
description: Sets up the toolchain for the project
inputs:
  platform:
    description: The target platform to set up toolchain for
  variant:
    description: Whether we're building from example, template, etc.
runs:
  using: composite
  steps:
    - name: Set up Ccache
      if: ${{ inputs.platform == 'ios' || inputs.platform == 'macos' }}
      run: |
        if ! command -v ccache 1> /dev/null; then
          brew install ccache
        fi

        CCACHE_HOME=$(dirname $(dirname $(which ccache)))/opt/ccache

        echo "CCACHE_DIR=$(git rev-parse --show-toplevel)/.ccache" >> $GITHUB_ENV

        echo "CC=${CCACHE_HOME}/libexec/clang" >> $GITHUB_ENV
        echo "CXX=${CCACHE_HOME}/libexec/clang++" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER_LAUNCHER=$(which ccache)" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=$(which ccache)" >> $GITHUB_ENV

        ccache --zero-stats 1> /dev/null
      shell: bash
    - name: Set up Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18
        cache: yarn
    - name: Set up JDK
      uses: actions/setup-java@v3.10.0
      with:
        distribution: temurin
        java-version: 11
    - name: Set up MSBuild
      if: ${{ inputs.platform == 'windows' }}
      uses: microsoft/setup-msbuild@v1.3
    - name: Set up Ruby
      if: ${{ inputs.platform == 'ios' || inputs.platform == 'macos' || inputs.platform == 'node' }}
      uses: ruby/setup-ruby@v1.137.2
      with:
        ruby-version: "3.0"
        bundler: Gemfile.lock
        bundler-cache: true
    - name: Set up VSTest.console.exe
      if: ${{ inputs.platform == 'windows' }}
      uses: darenm/Setup-VSTest@v1.2
    - name: Generate cache key
      id: cache-key-generator
      run: |
        if [[ -f example/${{ inputs.platform }}/Podfile.lock ]]; then
          clang --version > .clang-version
          echo "cache-key=$(node scripts/shasum.mjs .clang-version .yarnrc.yml example/${{ inputs.platform }}/Podfile.lock)" >> $GITHUB_OUTPUT
        else
          echo 'cache-key=false' >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Cache /.ccache
      if: ${{ steps.cache-key-generator.outputs.cache-key != 'false' }}
      uses: actions/cache@v3
      with:
        path: .ccache
        key: ${{ runner.os }}-${{ inputs.variant }}-ccache-${{ steps.cache-key-generator.outputs.cache-key }}
        restore-keys: ${{ runner.os }}-${{ inputs.variant }}-ccache-
